#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const replaceEscapes = (regexFactory) => (
  // request the regex
  regexFactory()
    // convert regex to string so we can replace things
    .toString()
    // replace \u escapes
    .replace(/\\u{?([a-zA-Z0-9]{2,8})}?/g, '\\x{$1}')
    // replace incompatible single-byte escapes
    .replace(/\\x([a-zA-Z0-9]{2})/g, '\\x{00$1}')
    // remove incompatible flags
    .slice(0, -2)
);

const emojiRegexRGI = replaceEscapes(require('emoji-regex/es2015/RGI_Emoji'));
const emojiRegex = replaceEscapes(require('emoji-regex/es2015'));
const emojiRegexText = replaceEscapes(require('emoji-regex/es2015/text'));

const input = fs.readFileSync(path.join(__dirname, './template.cr'), 'utf8');

const output = input
  .replace('/% emojiRegexRGI %/', emojiRegexRGI)
  .replace('/% emojiRegex %/', emojiRegex)
  .replace('/% emojiRegexText %/', emojiRegexText);

fs.writeFileSync(path.join(__dirname, '../src/emoji_regex.cr'), output);